const ACTION_TYPE = {
  ADD_TODO_ITEM: "ADD_TODO_ITEM",
  REMOVE_TODO_ITEM: "REMOVE_TODO_ITEM",
  MARK_COMPLETED: "MARK_COMPLETED",
  UPDATE_TODO_ITEM: "UPDATE_TODO_ITEM",
};

export const FILTER_TITLES = ["ALL", "ACTIVE", "COMPLETED"];

export default ACTION_TYPE;
